#!/usr/bin/env bash
# Bootstrap defaults. All values can be overridden through the environment.

bootstrap_load_config() {
    BOOTSTRAP_VERSION="1.4.0"

    WORKSPACE_ROOT="${WORKSPACE_ROOT:-/workspace}"
    TOOLS_ROOT="${TOOLS_ROOT:-$WORKSPACE_ROOT/tools}"
    PROJECTS_ROOT="${PROJECTS_ROOT:-$WORKSPACE_ROOT/projects}"
    DATA_ROOT="${DATA_ROOT:-$WORKSPACE_ROOT/data}"
    MODELS_ROOT="${MODELS_ROOT:-$WORKSPACE_ROOT/models}"
    OUTPUTS_ROOT="${OUTPUTS_ROOT:-$WORKSPACE_ROOT/outputs}"
    VENV_ROOT="${VENV_ROOT:-$WORKSPACE_ROOT/venvs}"
    CACHE_ROOT="${CACHE_ROOT:-$WORKSPACE_ROOT/.cache}"
    LOG_ROOT="${LOG_ROOT:-$WORKSPACE_ROOT/startup-logs}"
    STATE_ROOT="${STATE_ROOT:-$WORKSPACE_ROOT/.setup-state}"

    RUN_APT_UPGRADE="${RUN_APT_UPGRADE:-0}"
    INSTALL_ZSH="${INSTALL_ZSH:-1}"
    INSTALL_OH_MY_ZSH="${INSTALL_OH_MY_ZSH:-1}"
    INSTALL_NODEJS="${INSTALL_NODEJS:-1}"
    INSTALL_CLAUDE_CODE="${INSTALL_CLAUDE_CODE:-1}"
    INSTALL_CODEX="${INSTALL_CODEX:-1}"
    INSTALL_VSCODE_EXTENSIONS="${INSTALL_VSCODE_EXTENSIONS:-1}"
    INSTALL_UV="${INSTALL_UV:-1}"
    INSTALL_BASE_PYTHON_ENV="${INSTALL_BASE_PYTHON_ENV:-1}"
    INSTALL_RUNTIME_TOOLS="${INSTALL_RUNTIME_TOOLS:-1}"
    RUN_ACCEPT_TEST="${RUN_ACCEPT_TEST:-1}"

    BASE_PYTHON_ENV="${BASE_PYTHON_ENV:-$VENV_ROOT/base-python}"
    BASE_PYTHON_PACKAGES="${BASE_PYTHON_PACKAGES:-numpy}"

    UV_VERSION="${UV_VERSION:-0.9.2}"
    UV_SHA256="${UV_SHA256:-b775bb84c72210c6c0b9670cfaad0ac2e3953f12a2947d52b57603b4fbae3798}"
    OH_MY_ZSH_REF="${OH_MY_ZSH_REF:-677a4592b18c08ddea737f8aca70bac0e9fc9313}"
    OH_MY_ZSH_SHA256="${OH_MY_ZSH_SHA256:-}"
    OH_MY_ZSH_THEME="${OH_MY_ZSH_THEME:-robbyrussell}"
    OH_MY_ZSH_PLUGINS="${OH_MY_ZSH_PLUGINS:-git}"

    NODE_VERSION="${NODE_VERSION:-24.18.0}"
    NODE_SHA256_X64="${NODE_SHA256_X64:-55aa7153f9d88f28d765fcdad5ae6945b5c0f98a36881703817e4c450fa76742}"
    NODE_SHA256_ARM64="${NODE_SHA256_ARM64:-58c9520501f6ae2b52d5b210444e24b9d0c029a58c5011b797bc1fe7105886f6}"
    NODE_INSTALL_ROOT="${NODE_INSTALL_ROOT:-/opt/nodejs}"

    AI_CLI_PREFIX="${AI_CLI_PREFIX:-/opt/gpu-ai-cli}"
    NPM_REGISTRY="${NPM_REGISTRY:-https://registry.npmjs.org/}"
    CLAUDE_CODE_VERSION="${CLAUDE_CODE_VERSION:-2.1.216}"
    CLAUDE_CODE_DISABLE_AUTOUPDATER="${CLAUDE_CODE_DISABLE_AUTOUPDATER:-1}"
    CODEX_VERSION="${CODEX_VERSION:-0.145.0}"

    VSCODE_EXTENSIONS_FILE="${VSCODE_EXTENSIONS_FILE:-$ROOT/config/vscode-extensions.txt}"
    VSCODE_EXTENSIONS_STRICT="${VSCODE_EXTENSIONS_STRICT:-0}"
    VSCODE_EXTENSIONS_AUTO_RETRY_SECONDS="${VSCODE_EXTENSIONS_AUTO_RETRY_SECONDS:-21600}"

    INSTALL_ADDON="${INSTALL_ADDON:-0}"
    ADDON_NAME="${ADDON_NAME:-}"
    ADDON_VERSION="${ADDON_VERSION:-}"
    ADDON_URL="${ADDON_URL:-}"
    ADDON_SHA256="${ADDON_SHA256:-}"
    ADDON_INSTALLER="${ADDON_INSTALLER:-install.sh}"
    ADDON_INSTALL_ARGS="${ADDON_INSTALL_ARGS:-}"
    ADDON_FORCE="${ADDON_FORCE:-0}"
    ADDON_ALLOW_LOCAL_FILE="${ADDON_ALLOW_LOCAL_FILE:-0}"
}
