#!/usr/bin/env bash

# One root-only file holds every provider API key, and the generated Zsh
# startup configuration loads it. Deliberately not /etc/profile.d: that
# directory is world-readable and applies to every user on the box.

bootstrap_write_secrets_zsh() {
    local zsh_dir loader
    zsh_dir=/root/.config/zsh
    loader="$SECRETS_DIR/secrets-load.sh"
    mkdir -p "$zsh_dir"

    cat > "$zsh_dir/server-secrets.zsh" <<ZSHEOF
# generated by server-bootstrap v$BOOTSTRAP_VERSION
export SERVER_SECRETS_FILE=$SECRETS_FILE
if [ -f $loader ]; then
    . $loader
    server_secrets_load
fi

aikeys() {
    case "\${1:-status}" in
        on)
            server_secrets_load
            printf 'API keys loaded from %s\n' "\$SERVER_SECRETS_FILE"
            ;;
        off)
            server_secrets_unload
            printf 'API keys cleared from this shell; claude and codex will use subscription login\n'
            ;;
        status) server_secrets_status ;;
        *) printf 'Usage: aikeys [status|on|off]\n' >&2; return 2 ;;
    esac
}
ZSHEOF
    chmod 0644 "$zsh_dir/server-secrets.zsh"
}

bootstrap_secrets() {
    SECRETS_RESULT="disabled"
    [[ "$INSTALL_SECRETS_FILE" == 1 ]] || return 0

    mkdir -p "$SECRETS_DIR"
    chmod 0700 "$SECRETS_DIR"

    # The loader is copied beside the keys file so an interactive shell works
    # even when INSTALL_RUNTIME_TOOLS is off.
    [[ -f "$SECRETS_LOADER" ]] \
        || { sb_die "secrets loader not found: $SECRETS_LOADER"; return; }
    install -m 0644 "$SECRETS_LOADER" "$SECRETS_DIR/secrets-load.sh"

    if [[ -e "$SECRETS_FILE" ]]; then
        chmod 0600 "$SECRETS_FILE"
        sb_log "kept existing keys file: $SECRETS_FILE"
    elif [[ -f "$SECRETS_TEMPLATE" ]]; then
        install -m 0600 "$SECRETS_TEMPLATE" "$SECRETS_FILE"
        sb_log "created keys file from template: $SECRETS_FILE"
    else
        printf '%s\n' 'ANTHROPIC_API_KEY=' 'OPENAI_API_KEY=' 'OPENROUTER_API_KEY=' > "$SECRETS_FILE"
        chmod 0600 "$SECRETS_FILE"
        sb_log "created keys file: $SECRETS_FILE"
    fi

    bootstrap_write_secrets_zsh
    SECRETS_RESULT="$SECRETS_FILE"
}
