#!/usr/bin/env bash

bootstrap_install_oh_my_zsh_archive() {
    local temp archive source_dir
    temp="$(mktemp -d)"
    archive="$temp/oh-my-zsh.tar.gz"
    if ! sb_fetch_verified \
        "https://github.com/ohmyzsh/ohmyzsh/archive/$OH_MY_ZSH_REF.tar.gz" \
        "$OH_MY_ZSH_SHA256" "$archive"; then
        rm -rf -- "$temp"
        return 1
    fi
    if ! sb_extract_archive "$archive" "$temp/extracted"; then
        rm -rf -- "$temp"
        return 1
    fi
    source_dir="$(find "$temp/extracted" -mindepth 1 -maxdepth 1 -type d -print -quit)"
    [[ -n "$source_dir" ]] || { rm -rf -- "$temp"; sb_die "Oh My Zsh archive was empty"; return; }
    rm -rf -- /root/.oh-my-zsh
    mv -- "$source_dir" /root/.oh-my-zsh
    rm -rf -- "$temp"
}

bootstrap_install_oh_my_zsh_git() {
    [[ "$OH_MY_ZSH_REF" =~ ^[0-9a-fA-F]{40}$ ]] \
        || { sb_die "OH_MY_ZSH_REF must be a full 40-character commit when no archive checksum is supplied"; return; }

    if [[ -f /root/.oh-my-zsh/oh-my-zsh.sh && -d /root/.oh-my-zsh/.git ]]; then
        local installed_ref
        installed_ref="$(git -C /root/.oh-my-zsh rev-parse HEAD 2>/dev/null || true)"
        [[ "${installed_ref,,}" != "${OH_MY_ZSH_REF,,}" ]] || return 0
    fi

    local temp repo actual_ref
    temp="$(mktemp -d)"
    repo="$temp/oh-my-zsh"
    git init -q "$repo"
    git -C "$repo" remote add origin https://github.com/ohmyzsh/ohmyzsh.git
    if ! sb_retry 4 git -C "$repo" fetch --depth 1 origin "$OH_MY_ZSH_REF"; then
        rm -rf -- "$temp"
        return 1
    fi
    git -C "$repo" checkout -q --detach FETCH_HEAD
    actual_ref="$(git -C "$repo" rev-parse HEAD)"
    [[ "${actual_ref,,}" == "${OH_MY_ZSH_REF,,}" ]] \
        || { rm -rf -- "$temp"; sb_die "Oh My Zsh commit verification failed"; return; }

    rm -rf -- /root/.oh-my-zsh
    mv -- "$repo" /root/.oh-my-zsh
    rm -rf -- "$temp"
}

bootstrap_oh_my_zsh() {
    [[ "$INSTALL_OH_MY_ZSH" == 1 ]] || return 0
    [[ -n "$OH_MY_ZSH_REF" ]] \
        || { sb_die "Oh My Zsh requested but OH_MY_ZSH_REF is empty"; return; }

    if [[ -n "$OH_MY_ZSH_SHA256" ]]; then
        sb_valid_sha256 "$OH_MY_ZSH_SHA256" \
            || { sb_die "invalid OH_MY_ZSH_SHA256"; return; }
        bootstrap_install_oh_my_zsh_archive
    else
        bootstrap_install_oh_my_zsh_git
    fi
    [[ -f /root/.oh-my-zsh/oh-my-zsh.sh ]] \
        || { sb_die "Oh My Zsh installation is incomplete"; return; }
}

bootstrap_set_default_zsh() {
    local zsh_path current_shell
    zsh_path="$(command -v zsh 2>/dev/null || true)"
    [[ -n "$zsh_path" ]] || { sb_die "Zsh was requested but is not installed"; return; }
    zsh_path="$(readlink -f -- "$zsh_path")"

    touch /etc/shells
    sb_ensure_line /etc/shells "$zsh_path"
    current_shell="$(getent passwd root | awk -F: '{print $7}')"
    if [[ "$current_shell" != "$zsh_path" ]]; then
        if command -v usermod >/dev/null 2>&1; then
            usermod --shell "$zsh_path" root
        else
            chsh -s "$zsh_path" root
        fi
    fi
    current_shell="$(getent passwd root | awk -F: '{print $7}')"
    [[ "$current_shell" == "$zsh_path" ]] \
        || { sb_die "failed to set Zsh as root's default login shell"; return; }
}

bootstrap_write_zsh_config() {
    local zsh_dir common init old_line temp_zshrc plugin
    local -a plugins
    zsh_dir=/root/.config/zsh
    common="$zsh_dir/server-common.zsh"
    init="$zsh_dir/bootstrap-init.zsh"
    mkdir -p "$zsh_dir"

    cat > "$common" <<ZSHEOF
# generated by server-bootstrap v$BOOTSTRAP_VERSION
alias c='clear'
alias ll='ls -alFh'
alias la='ls -A'
alias ..='cd ..'
alias ...='cd ../..'
alias disk='df -h'
alias mem='free -h'
alias work='cd $WORKSPACE_ROOT'
mkcd() {
    [[ \$# -eq 1 ]] || { echo "Usage: mkcd DIRECTORY" >&2; return 2; }
    mkdir -p -- "\$1" && cd -- "\$1"
}
[ -f $CACHE_ENV ] && source $CACHE_ENV
ZSHEOF
    if [[ "$INSTALL_VSCODE_EXTENSIONS" == 1 ]]; then
        cat >> "$common" <<ZSHEOF
if [[ -n "\${VSCODE_IPC_HOOK_CLI:-}" && -x /usr/local/bin/server-vscode-extensions ]]; then
    VSCODE_EXTENSIONS_AUTO_RETRY_SECONDS=$VSCODE_EXTENSIONS_AUTO_RETRY_SECONDS \
        /usr/local/bin/server-vscode-extensions --auto >/dev/null 2>&1 &!
fi
ZSHEOF
    fi
    command -v ss >/dev/null 2>&1 && echo "alias ports='ss -ltnp'" >> "$common"
    command -v python3 >/dev/null 2>&1 && echo "alias py='python3'" >> "$common"
    command -v nvidia-smi >/dev/null 2>&1 && printf "%s\n%s\n" \
        "alias gpu='nvidia-smi'" "alias gpu-watch='watch -n 1 nvidia-smi'" >> "$common"

    : > "$init"
    printf '# generated by server-bootstrap v%s\n' "$BOOTSTRAP_VERSION" >> "$init"
    if [[ "$INSTALL_OH_MY_ZSH" == 1 ]]; then
        read -r -a plugins <<< "$OH_MY_ZSH_PLUGINS"
        for plugin in "${plugins[@]}"; do
            [[ "$plugin" =~ ^[A-Za-z0-9._-]+$ ]] \
                || { sb_die "invalid Oh My Zsh plugin name: $plugin"; return; }
        done
        printf 'export ZSH=%q\n' /root/.oh-my-zsh >> "$init"
        printf 'ZSH_THEME=%q\n' "$OH_MY_ZSH_THEME" >> "$init"
        printf 'plugins=(' >> "$init"
        for plugin in "${plugins[@]}"; do printf ' %q' "$plugin" >> "$init"; done
        printf ' )\n' >> "$init"
        printf "zstyle ':omz:update' mode disabled\n" >> "$init"
        printf 'source "$ZSH/oh-my-zsh.sh"\n' >> "$init"
    fi
    printf '[ -f %q ] && source %q\n' "$common" "$common" >> "$init"

    touch /root/.zshrc
    old_line="[ -f $common ] && source $common"
    temp_zshrc="$(mktemp)"
    grep -Fvx "$old_line" /root/.zshrc > "$temp_zshrc" || true
    cat "$temp_zshrc" > /root/.zshrc
    rm -f -- "$temp_zshrc"
    sb_ensure_line /root/.zshrc "[ -f $init ] && source $init"
}

bootstrap_shell() {
    [[ "$INSTALL_ZSH" == 1 ]] || return 0
    bootstrap_oh_my_zsh
    bootstrap_write_zsh_config
    bootstrap_set_default_zsh
}
